In [10]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.10.2'

In [3]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [6]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [7]:
len(x)

4

In [8]:
x.shape

torch.Size([4])

In [14]:
a = torch.arange(6).reshape(3, 2)

In [15]:
a.shape

torch.Size([3, 2])

In [16]:
a.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [17]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # Assign a copy of `A` to `B` by allocating new memory
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [20]:
A*B # element wise

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [26]:
a=np.arange(20).reshape(5, 4)
b=a.copy()

In [27]:
a*b

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]])

numpy and torch have simmilar array processing technqiues 

In [29]:
A.mean(),A.sum()

(tensor(9.5000), tensor(190.))

In [30]:
A.sum(axis=0), A.sum(axis=1)

(tensor([40., 45., 50., 55.]), tensor([ 6., 22., 38., 54., 70.]))

In [31]:
A.sum(axis=1, keepdims=True)

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [32]:
A.sum(axis=0, keepdims=True)

tensor([[40., 45., 50., 55.]])

In [33]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [36]:
x = torch.arange(4, dtype = torch.float32)
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [37]:
torch.sum(x * y)

tensor(6.)

In [38]:
torch.mv(A, x) # Matrix*Vector product

tensor([ 14.,  38.,  62.,  86., 110.])

In [40]:
torch.sum(A*x,axis=1)

tensor([ 14.,  38.,  62.,  86., 110.])

In [41]:
B = torch.ones(4, 3) 
torch.mm(A, B) # Matrix-matrix multiplication

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [42]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [43]:
torch.abs(u).sum()

tensor(7.)

# autograd

In [45]:
x = torch.arange(4.0)

In [48]:
x.requires_grad_(True)
x.grad

In [49]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [50]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [51]:
x.grad.zero_() # reset gradeints

tensor([0., 0., 0., 0.])

Sometimes, we wish to move some calculations outside of the recorded computational graph. 

In [52]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

# Probability

In [54]:
# rolling a die
fair_probs = torch.ones([6]) / 6
fair_probs

tensor([0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667])

In [60]:
torch.distributions.multinomial.Multinomial(10000,fair_probs).sample()/10000

tensor([0.1705, 0.1711, 0.1630, 0.1643, 0.1645, 0.1666])